In [2]:
from openalgo import api

client = api(api_key="46cff674c549ed49b63f9050d76659f9689ce426c64d555d3689de5f0fc2e6b9", host="http://127.0.0.1:5000")


response = client.history(
    symbol="NIFTY",
    exchange="NSE_INDEX",
    interval="1h",
    start_date="2026-01-01",
    end_date="2026-05-13",
)
response

,close,high,low,oi,open,volume
timestamp,,,,,,
2026-01-01 09:15:00+05:30,26151.15,26197.55,26147.00,0,26173.30,103824338
2026-01-01 10:15:00+05:30,26170.50,26185.60,26117.70,0,26151.65,45362012
2026-01-01 11:15:00+05:30,26125.00,26177.75,26123.95,0,26169.30,56788590
2026-01-01 12:15:00+05:30,26151.45,26162.55,26113.40,0,26124.35,85018686
2026-01-01 13:15:00+05:30,26168.00,26176.20,26129.70,0,26150.80,47031663
...,...,...,...,...,...,...
2026-05-13 11:15:00+05:30,23512.75,23514.15,23392.75,0,23403.80,47019771
2026-05-13 12:15:00+05:30,23538.50,23582.95,23423.30,0,23511.95,55564366
2026-05-13 13:15:00+05:30,23516.80,23540.50,23480.25,0,23538.00,41690498
2026-05-13 14:15:00+05:30,23425.70,23522.40,23402.85,0,23516.50,79313371
2026-05-13 15:15:00+05:30,23428.70,23436.95,23394.35,0,23425.40,36301106

In [3]:
response = client.history(
    symbol="NIFTY",
    exchange="NSE_INDEX",
    interval="D",
    start_date="2025-10-01",
    end_date="2025-10-10",
)
response

               close      high       low  oi      open  volume
timestamp
2025-10-01  24836.30  24867.95  24605.95   0  24620.55       0
2025-10-03  24894.25  24904.80  24747.55   0  24759.55       0
2025-10-06  25077.65  25095.95  24881.65   0  24916.55       0
2025-10-07  25108.30  25220.90  25076.30   0  25085.30       0
2025-10-08  25046.15  25192.50  25008.50   0  25079.75       0
2025-10-09  25181.80  25199.25  25024.30   0  25074.30       0
2025-10-10  25285.35  25330.75  25156.85   0  25167.65       0

In [4]:
client.interval()

{'data': {'days': ['D'],
  'hours': ['1h', '2h', '3h', '4h'],
  'minutes': ['1m', '2m', '3m', '5m', '10m', '15m', '30m', '60m'],
  'months': ['M'],
  'seconds': [],
  'weeks': ['W']},
 'status': 'success'}